"""C3 gate for the console (issue #8): shared user-visible copy is
defined in the minder_web copy modules and referenced from there - never
hardcoded in template or services source.

Issue #12 split the copy across modules to hold the C2 line budget:
strings_base (the shared S), strings_copy (answer and action
composers), strings_pages, strings_scorecard and strings_session
(page sections app.py merges into S). The gate reads the union, so a
page section cannot silently drop out of the Jinja global."""
from pathlib import Path

import minder_web.strings_base as strings_base
import minder_web.strings_copy as strings_copy
import minder_web.strings_pages as strings_pages
import minder_web.strings_scorecard as strings_scorecard
import minder_web.strings_session as strings_session

TEMPLATE_DIR = Path(strings_base.__file__).parent / "templates"

# Every module that owns console copy. A new copy module must be added
# here, which is what makes a dropped merge into S a test failure.
COPY_MODULES = (strings_base, strings_copy, strings_pages,
                strings_scorecard, strings_session)

# Copy that is shared, repeated, or generated by minder_web.services:
# the drift-prone strings C3 exists for. Page-local single words stay
# page-local; this list is the module's contract.
SHARED_PHRASES = (
    "how am I doing?",
    "what happened?",
    "what has it learned?",
    "running on",
    "what to improve first",
    "weekly workflow summary",
    "operator focus",
    "current flags",
    "observed workflow evidence only",
    "not available",
    "recording:",
    "nothing flagged for this window.",
    "tool calls saved",
    "save path ready",
    "n/a",
)


def _iter_values(obj):
    if isinstance(obj, str):
        yield obj
    elif isinstance(obj, dict):
        for value in obj.values():
            yield from _iter_values(value)
    elif isinstance(obj, (tuple, list)):
        for value in obj:
            yield from _iter_values(value)


def _module_values():
    for module in COPY_MODULES:
        for name in dir(module):
            if not name.startswith("_"):
                yield from _iter_values(getattr(module, name))


def test_shared_copy_is_defined_in_strings_module():
    defined = list(_module_values())
    for phrase in SHARED_PHRASES:
        assert any(phrase in value for value in defined), \
            f"copy missing from the minder_web copy modules: {phrase!r}"


def test_every_copy_section_reaches_the_templates():
    """The Jinja global `S` must carry every copy module's section, and
    every `S.<section>.<key>` a template names must resolve. A section
    that exists in a module but never reaches S renders nothing."""
    from minder_web import app as app_module
    import re

    global_s = app_module.templates.env.globals["S"]
    assert set(global_s) >= {"scorecard", "session", "domains"}
    assert global_s["session"]["work"] == \
        strings_session.SESSION["work"]
    assert global_s["scorecard"]["focus"] == \
        strings_scorecard.SCORECARD["focus"]
    assert global_s["domains"]["title"] == \
        strings_pages.DOMAINS["title"]

    needed = set()
    for template in sorted(TEMPLATE_DIR.glob("*.html")):
        needed.update(re.findall(r"S\.([a-z_]+)\.([a-z_0-9]+)",
                                 template.read_text()))
    missing = sorted(f"S.{s}.{k}" for s, k in needed
                     if not isinstance(global_s.get(s), dict)
                     or k not in global_s[s])
    assert missing == [], f"template names copy that never reaches S: {missing}"


def test_templates_do_not_hardcode_shared_copy():
    templates = sorted(TEMPLATE_DIR.glob("*.html"))
    assert len(templates) >= 15, \
        f"only {len(templates)} templates scanned (M2)"
    for template in templates:
        source = template.read_text()
        for phrase in SHARED_PHRASES:
            assert phrase not in source, \
                f"{template.name} hardcodes {phrase!r} (C3: use S.*)"


def test_services_does_not_hardcode_shared_copy():
    # ast, not grep: copy lives in string literals; docstrings may name
    # copy when explaining behavior
    import ast
    import minder_web.services as services
    tree = ast.parse(Path(services.__file__).read_text())
    docstrings = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.FunctionDef, ast.ClassDef,
                             ast.AsyncFunctionDef)):
            doc = ast.get_docstring(node, clean=False)
            if doc is not None:
                docstrings.add(doc)
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            if node.value in docstrings:
                continue
            for phrase in SHARED_PHRASES:
                assert phrase not in node.value, \
                    f"services.py hardcodes {phrase!r} (C3: import from " \
                    "minder_web copy modules)"
