"""C3 gate for the console (issue #8): shared user-visible copy is
defined in minder_web.strings and referenced from there - never
hardcoded in template or services source."""
from pathlib import Path

import minder_web.strings as strings

TEMPLATE_DIR = Path(strings.__file__).parent / "templates"

# Copy that is shared, repeated, or generated by minder_web.services:
# the drift-prone strings C3 exists for. Page-local single words stay
# page-local; this list is the module's contract.
SHARED_PHRASES = (
    "how am I doing?",
    "what happened?",
    "what has it learned?",
    "running on",
    "what to improve first",
    "weekly workflow summary",
    "operator focus",
    "current flags",
    "observed workflow evidence only",
    "not available",
    "recording:",
    "nothing flagged for this window.",
    "tool calls saved",
    "save path ready",
    "n/a",
)


def _iter_values(obj):
    if isinstance(obj, str):
        yield obj
    elif isinstance(obj, dict):
        for value in obj.values():
            yield from _iter_values(value)
    elif isinstance(obj, (tuple, list)):
        for value in obj:
            yield from _iter_values(value)


def _module_values():
    for name in dir(strings):
        if not name.startswith("_"):
            yield from _iter_values(getattr(strings, name))


def test_shared_copy_is_defined_in_strings_module():
    defined = list(_module_values())
    for phrase in SHARED_PHRASES:
        assert any(phrase in value for value in defined), \
            f"copy missing from minder_web.strings: {phrase!r}"


def test_templates_do_not_hardcode_shared_copy():
    templates = sorted(TEMPLATE_DIR.glob("*.html"))
    assert len(templates) >= 15, \
        f"only {len(templates)} templates scanned (M2)"
    for template in templates:
        source = template.read_text()
        for phrase in SHARED_PHRASES:
            assert phrase not in source, \
                f"{template.name} hardcodes {phrase!r} (C3: use S.*)"


def test_services_does_not_hardcode_shared_copy():
    # ast, not grep: copy lives in string literals; docstrings may name
    # copy when explaining behavior
    import ast
    import minder_web.services as services
    tree = ast.parse(Path(services.__file__).read_text())
    docstrings = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.FunctionDef, ast.ClassDef,
                             ast.AsyncFunctionDef)):
            doc = ast.get_docstring(node, clean=False)
            if doc is not None:
                docstrings.add(doc)
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            if node.value in docstrings:
                continue
            for phrase in SHARED_PHRASES:
                assert phrase not in node.value, \
                    f"services.py hardcodes {phrase!r} (C3: import from " \
                    "minder_web.strings)"
