"""Turn a *confirmed* trace failure into a benchmark regression case.

The evidence chain this closes (PRD §20):

    trace → finding → reviewer confirmation → regression case

Two gates, both deliberate:

1. **The finding must be failure-shaped.** A concrete defective behaviour
   a test can encode — a loop, an ungrounded edit, an unverified change,
   no progress. Advisory judgements (call volume, a repeated command) are
   not converted: encoding "fewer calls" as a test is the prescriptive
   trap the product explicitly avoids.
2. **The finding must be confirmed by a human.** A finding nobody has
   judged is a hypothesis; promoting it to the regression suite would let
   an evaluator's false positive become the standard. The gate is a
   `trace feedback --finding <id> --verdict confirm` row, so the
   conversion always has a recorded approver.

Generated files are validated against the suite's own manifest rules
*before* the manifest is written. `validate_manifest` checks fixture
existence on disk, so the files must be staged first; on any validation
error the staged directory is removed and the manifest is restored
byte-for-byte, leaving nothing behind.
"""
import json
import re
import shutil
import sys
from pathlib import Path

from minder_trace import normalize
from . import benchmark as bench

# Evaluators whose findings describe a defective behaviour, not a
# judgement call.
FAILURE_EVALUATORS = frozenset((
    "duplicate_retry", "success_loop", "evidence_gap", "unverified_change",
    "no_progress", "workflow",
))
# Book-keeping / self-reporting rules that are never a failure in
# themselves.
NON_FAILURE_RULES = frozenset((
    "success-loop-suppressed", "evaluator-error", "minder-intervened",
    "tool-call-budget", "repeated-identical-command",
))
MIN_SEVERITY = ("medium", "high", "blocker")

# How many recorded repeats to embed. Enough to trip the rule, small
# enough to read and to diff.
SCENARIO_CAP = 6

REPO_ROOT = Path(__file__).resolve().parents[1]

GENERATED_HEADER = (
    '"""Generated by minder-op trace regress from review {review_id}, '
    'finding {finding_id} — DRAFT, review before use.\n\n'
    "Source session: {session_id}\n"
    "Rule: {rule_id} ({evaluator}, {severity})\n"
    "Recorded: {message}\n\n"
    "The 8D runner is deferred, so this case is content-only: the 8C "
    "manifest validates it and the comparator can cite it, but nothing "
    "executes it yet.\n"
    '"""\n'
)


def _slug(text, cap=40):
    clean = re.sub(r"[^a-z0-9]+", "_", str(text or "").lower()).strip("_")
    return clean[:cap] or "case"


def default_task_id(finding):
    import hashlib
    digest = hashlib.sha1(
        str(finding.get("finding_id") or "").encode()).hexdigest()[:6]
    return f"tr_{_slug(finding.get('evaluator'), 20)}_{digest}"


def is_failure_shaped(finding):
    """Whether this finding is a thing a test can assert, and is severe
    enough to be worth one."""
    if not isinstance(finding, dict):
        return False
    if finding.get("rule_id") in NON_FAILURE_RULES:
        return False
    if finding.get("evaluator") not in FAILURE_EVALUATORS:
        return False
    return (finding.get("severity") or "info") in MIN_SEVERITY


def select_events(run, finding):
    """The recorded events that constitute the failure.

    For `no_progress` the evidence holds only the streak's first and last
    sequence, so the span between them is the scenario — reconstructing
    just those two events would not reproduce anything."""
    events = run.get("events") or []
    seqs = [s for s in (finding.get("evidence", {}).get("ds_seqs") or [])
            if s is not None]
    if not seqs:
        return []
    if finding.get("evaluator") == "no_progress":
        low, high = min(seqs), max(seqs)
        chosen = [e for e in events
                  if e.get("ds_seq") is not None and low <= e["ds_seq"]
                  <= high]
    else:
        wanted = set(seqs)
        chosen = [e for e in events if e.get("ds_seq") in wanted]
    return chosen[:SCENARIO_CAP]


def _call_record(seq, call_id, tool, arguments):
    return {"type": "tool/call", "seq": seq, "time": seq * 1000,
            "data": {"turn": 1, "step": 1, "callId": call_id,
                     "name": tool or "bash", "arguments": arguments}}


def _result_record(seq, call_id, text):
    return {"type": "tool/result", "seq": seq, "time": seq * 1000,
            "data": {"turn": 1, "step": 1,
                     "message": {
                         "source": {"kind": "tool", "callId": call_id},
                         "content": [{
                             "type": "tool-result", "toolCallId": call_id,
                             "content": [{"type": "text", "text": text}],
                         }],
                     }}}


def records_for(events, *, start_seq=1, prefix=None, suffix=None):
    """Rebuild DSH session records from normalized events, so a generated
    case replays through the same normalizer and evaluators as the
    original trace."""
    records = []
    seq = start_seq
    for item in list(prefix or ()) + list(events) + list(suffix or ()):
        if isinstance(item, dict) and "record" in item:
            records.append(item["record"])
            seq = max(seq, int(item["record"].get("seq") or seq)) + 1
            continue
        event = item
        call_id = f"g{seq}"
        tool = event.get("tool") or "bash"
        try:
            arguments = json.dumps(json.loads(event.get("args_json")
                                              or "{}"))
        except (ValueError, TypeError):
            arguments = "{}"
        records.append(_call_record(seq, call_id, tool, arguments))
        records.append(_result_record(seq + 1, call_id,
                                      event.get("error_excerpt") or ""))
        seq += 2
    return records


def correction_for(run, finding, events):
    """A corrected replay that the same rule must NOT flag.

    This is what makes the case a *regression* test rather than a
    snapshot: it pins both that the failure is detectable and that the
    fix silences it. Returns records, or None when no mechanical
    correction exists (a missing required tool cannot be conjured from the
    trace)."""
    rule = finding.get("rule_id")
    if rule in ("dup-unchanged-retry", "success-loop-same-result",
                "no-new-artifact"):
        return records_for(events[:1])
    if rule == "edit-without-test":
        suffix = [{"record": _call_record(
            900, "gp", "bash", json.dumps({"command":
                                           "python3 -m pytest -q"}))},
            {"record": _result_record(901, "gp", "1 passed")}]
        return records_for(events, suffix=suffix)
    if rule == "edit-without-read":
        path = ((events[0].get("file_path") if events else "")
                or "/repo/file.py")
        prefix = [{"record": _call_record(
            900, "gr", "read", json.dumps({"file_path": path}))},
            {"record": _result_record(901, "gr", "current contents")}]
        return records_for(events, prefix=prefix)
    return None


def build_case(run, finding, task_id):
    """The two generated files, as strings. Pure — nothing is written."""
    events = select_events(run, finding)
    scenario = records_for(events)
    corrected = correction_for(run, finding, events)
    header = GENERATED_HEADER.format(
        review_id=finding.get("_review_id", "?"),
        finding_id=finding.get("finding_id"),
        session_id=(run.get("source") or {}).get("session_id"),
        rule_id=finding.get("rule_id"), evaluator=finding.get("evaluator"),
        severity=finding.get("severity"), message=finding.get("message"))
    task_py = (
        header
        + "\nimport json\n\n"
        + f'RULE_ID = {finding.get("rule_id")!r}\n'
        + f'EVALUATOR = {finding.get("evaluator")!r}\n'
        + f'TASK_ID = {task_id!r}\n\n'
        + "# The recorded action/result sequence that produced the finding.\n"
        + f"RECORDED = json.loads(r'''{json.dumps(scenario, indent=2)}''')\n\n"
        + ("# The same sequence with the failure corrected.\n"
           f"CORRECTED = json.loads(r'''{json.dumps(corrected, indent=2)}''')\n"
           if corrected else "CORRECTED = None\n")
    )
    test_py = (
        header
        + "\nimport sys\nfrom pathlib import Path\n\n\n"
        + "def _repo_root():\n"
        + '    """Locate the checkout.\n\n'
        + "    MINDER_REPO_ROOT wins (a sandboxed runner that copies the\n"
        + "    suite elsewhere has no way to walk up to it); otherwise walk\n"
        + "    up looking for the package markers. A fixed parent count\n"
        + "    would break as soon as the suite moved, and the failure would\n"
        + '    look like an unrelated ImportError."""\n'
        + "    import os\n"
        + '    env = os.environ.get("MINDER_REPO_ROOT")\n'
        + "    if env and (Path(env) / \"minder_trace\" / \"evaluate.py\").is_file():\n"
        + "        return Path(env)\n"
        + "    here = Path(__file__).resolve()\n"
        + "    for parent in here.parents:\n"
        + '        if (parent / "minder_trace" / "evaluate.py").is_file() and \\\n'
        + '                (parent / "minder_memory" / "canonicalise.py").is_file():\n'
        + "            return parent\n"
        + '    raise RuntimeError(\n'
        + '        "cannot locate the minder checkout above " + str(here)\n'
        + '        + "; set MINDER_REPO_ROOT if the suite was copied")\n\n\n'
        + "sys.path.insert(0, str(_repo_root()))\n\n"
        + "from minder_trace import evaluate, normalize  # noqa: E402\n"
        + "from task import CORRECTED, RECORDED, RULE_ID  # noqa: E402\n\n\n"
        + "def _rules(records):\n"
        + '    """Every rule_id an evaluator raises over these records."""\n'
        + "    run, report = normalize.normalize(records, session_id="
          '"regress", repo="/repo")\n'
        + "    return {f[\"rule_id\"] for f in evaluate.run_all(run, report)}"
          "\n\n\n"
        + "def test_the_recorded_failure_is_detected():\n"
        + '    """The case is only valid if the rule still catches it."""\n'
        + "    assert RULE_ID in _rules(RECORDED)\n\n\n"
        + "def test_the_corrected_behaviour_is_clean():\n"
        + '    """A weakened evaluator fails here: the case encodes the '
          'fix."""\n'
        + "    if CORRECTED is None:\n"
        + '        return  # no mechanical correction for this rule\n'
        + "    assert RULE_ID not in _rules(CORRECTED)\n"
    )
    return task_py, test_py, {
        "recorded_events": len(events),
        "has_correction": corrected is not None,
    }


def _write_case(suite_root, task_id, task_py, test_py):
    task_dir = Path(suite_root) / "tasks" / task_id
    task_dir.mkdir(parents=True, exist_ok=True)
    (task_dir / "task.py").write_text(task_py)
    (task_dir / f"test_{task_id}.py").write_text(test_py)
    return task_dir


def _manifest_entry(task_id, manifest, run, finding):
    forbidden = None
    for task in manifest.get("tasks") or ():
        if isinstance(task, dict) and isinstance(task.get("forbidden"), list):
            forbidden = list(task["forbidden"])
            break
    return {
        "task_id": task_id,
        "tier": 3,
        "family": "trace_regression",
        "title": (f"[{finding.get('evaluator')}] "
                  f"{(finding.get('message') or '')[:110]}"),
        "fixtures": [f"tasks/{task_id}/task.py",
                     f"tasks/{task_id}/test_{task_id}.py"],
        "expected": "tests_pass",
        "forbidden": forbidden or ["network", "package_install", "ssh",
                                   "writes_outside_sandbox"],
        "runner": {"kind": "pytest", "entry": [f"test_{task_id}.py"]},
        "source": {
            "review_id": finding.get("_review_id"),
            "finding_id": finding.get("finding_id"),
            "session_id": (run.get("source") or {}).get("session_id"),
            "run_id": run.get("run_id"),
            "rule_id": finding.get("rule_id"),
            "severity": finding.get("severity"),
        },
    }


def run(args, path):
    """CLI entry: `minder-op trace regress <session> --finding <id> --yes`."""
    from minder_memory import trace_reviews as reviews_mod

    loaded, report = normalize.load_session(args.session)
    if report.get("status") == "not_found":
        print("error: " + " ".join(report.get("notes") or []),
              file=sys.stderr)
        return 1
    session_id = (loaded.get("source") or {}).get("session_id")

    review = reviews_mod.latest_review(session_id, db_path=path)
    if review is None:
        print(f"error: no stored review for {session_id}. Run "
              f"`minder-op trace review {args.session}` with "
              "MINDER_TRACE_REVIEW=on first.", file=sys.stderr)
        return 1
    findings = review.get("findings") or []
    finding = next((f for f in findings
                    if f.get("finding_id") == args.finding), None)
    if finding is None:
        print(f"error: finding {args.finding} is not in review "
              f"{review['review_id']}", file=sys.stderr)
        return 1
    if not is_failure_shaped(finding):
        print(f"error: finding {args.finding} is not a failure-shaped "
              f"finding ({finding.get('evaluator')}/"
              f"{finding.get('rule_id')}, {finding.get('severity')}) — "
              "advisory findings are not converted into regression cases",
              file=sys.stderr)
        return 1

    verdicts = reviews_mod.finding_verdicts(review["review_id"],
                                            db_path=path)
    if verdicts.get(args.finding) != "confirm":
        print(f"error: finding {args.finding} has not been confirmed by a "
              "reviewer.", file=sys.stderr)
        print("A finding is a hypothesis until a human judges it; promoting "
              "an unconfirmed one would make an evaluator's false positive "
              "the standard.", file=sys.stderr)
        print(f"  confirm it with: minder-op trace feedback "
              f"{review['review_id']} --level run "
              f"--category evidence_quality --finding {args.finding} "
              f"--verdict confirm --yes", file=sys.stderr)
        return 1

    finding = dict(finding, _review_id=review["review_id"])
    task_id = args.task_id or default_task_id(finding)
    task_id = _slug(task_id, 60)
    try:
        suite_root = bench.suite_dir(args.suite)
    except bench.BenchmarkError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    manifest_path = Path(suite_root) / "manifest.json"
    try:
        manifest = bench.read_manifest(args.suite)
    except bench.BenchmarkError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    if any(t.get("task_id") == task_id
           for t in manifest.get("tasks") or ()):
        print(f"error: {args.suite} already has a task {task_id}",
              file=sys.stderr)
        return 1

    # Check the suite before touching it. `validate_manifest` resolves
    # fixture paths on disk, so a suite that is already broken (a fixture
    # that does not exist from here) would otherwise surface as "your
    # generated case does not validate", which is both wrong and
    # unactionable.
    pre_existing = bench.validate_manifest(manifest, suite_root)
    if pre_existing:
        print(f"error: suite {args.suite} is already invalid at "
              f"{suite_root}; refusing to add to it:", file=sys.stderr)
        for error in pre_existing:
            print(f"  {error}", file=sys.stderr)
        print("(fixture paths resolve relative to the suite directory, so "
              "a checkout missing the repo's sibling directories reads as "
              "invalid)", file=sys.stderr)
        return 1

    task_py, test_py, stats = build_case(loaded, finding, task_id)
    candidate = dict(manifest)
    candidate["tasks"] = list(manifest.get("tasks") or []) + [
        _manifest_entry(task_id, manifest, loaded, finding)]

    if not getattr(args, "yes", False):
        print("dry-run (pass --yes to write the case):")
        print(json.dumps({
            "suite": args.suite,
            "task_id": task_id,
            "files": [f"tasks/{task_id}/task.py",
                      f"tasks/{task_id}/test_{task_id}.py"],
            "manifest_entry": candidate["tasks"][-1],
            "recorded_events": stats["recorded_events"],
            "has_correction": stats["has_correction"],
        }, indent=2, sort_keys=True))
        return 0

    original = manifest_path.read_text()
    task_dir = None
    try:
        task_dir = _write_case(suite_root, task_id, task_py, test_py)
        manifest_path.write_text(json.dumps(candidate, indent=2) + "\n")
        errors = bench.validate_manifest(candidate, suite_root)
        if errors:
            manifest_path.write_text(original)
            shutil.rmtree(task_dir, ignore_errors=True)
            print("error: the generated case does not validate; nothing "
                  "written:", file=sys.stderr)
            for error in errors:
                print(f"  {error}", file=sys.stderr)
            return 1
    except OSError as exc:
        manifest_path.write_text(original)
        if task_dir is not None:
            shutil.rmtree(task_dir, ignore_errors=True)
        print(f"error: {exc}; nothing written", file=sys.stderr)
        return 1

    if getattr(args, "json", False):
        print(json.dumps({"task_id": task_id, "suite": args.suite,
                          "manifest_entry": candidate["tasks"][-1]},
                         indent=2, sort_keys=True))
    else:
        print(f"wrote {args.suite}/tasks/{task_id}/ "
              f"(task.py, test_{task_id}.py)")
        print(f"added {task_id} to {manifest_path}")
        print(f"  from review {review['review_id']}, finding "
              f"{args.finding} ({finding.get('rule_id')})")
        print("DRAFT: review the generated case before relying on it.")
    return 0
